# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(376, 372)
        MainWindow.setStyleSheet("color: black;\n"
"background-color: green;\n"
"border: 2px solid black;\n"
"border-radius: 5px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_number = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_number.setGeometry(QtCore.QRect(100, 130, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_number.setFont(font)
        self.cb_number.setStyleSheet("background-color: gray;")
        self.cb_number.setObjectName("cb_number")
        self.cd_aiphaber = QtWidgets.QCheckBox(self.centralwidget)
        self.cd_aiphaber.setGeometry(QtCore.QRect(100, 180, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cd_aiphaber.setFont(font)
        self.cd_aiphaber.setStyleSheet("background-color: gray;")
        self.cd_aiphaber.setObjectName("cd_aiphaber")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(130, 50, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(100, 100, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.bt_ok = QtWidgets.QPushButton(self.centralwidget)
        self.bt_ok.setGeometry(QtCore.QRect(140, 270, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_ok.setFont(font)
        self.bt_ok.setStyleSheet("background-color: gray;")
        self.bt_ok.setObjectName("bt_ok")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 376, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cb_number.setText(_translate("MainWindow", "Використовувати числа"))
        self.cd_aiphaber.setText(_translate("MainWindow", "Використовувати алфавіт"))
        self.title.setText(_translate("MainWindow", "Генератор паролів"))
        self.result.setText(_translate("MainWindow", "Тут буде результат"))
        self.bt_ok.setText(_translate("MainWindow", "Згенерувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
